name: Greeting
description: Greeting a person

inputs:
  name:
    description: "name on person"
    required: true

outputs:
  message:
    description: "Who get"
    value: ${{ steps.greet.outputs.message }}

runs:
  using: 'composite'
  steps:
    - name: "Say Hello"
      id: greet
      shell: bash
      run: |
        MSG="HELLO ${{ inputs.name }}"
        echo "message=$MSG" >> $GITHUB_OUTPUT
