name: context

on:
  push:

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Context Github
        run: echo '${{ toJson(github)}}'
      - name: Context job
        run: echo '${{ toJson(job)}}'
      - name: Context runner
        run: echo '${{ toJson(runner)}}'