name: context

on:
  push:

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Context Github
        run: echo '${{ github}}'
      - name: Context runner
        run: echo '${{ job}}'