name: dispath

on:
  workflow_dispatch:
    inputs:
      java_version:
        description: "java version"
        required: true
        default: "21"

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: java -version
      - name: node version
        run: node -v