name: SECRETS

on:
  push:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: print secret
        run: echo ${{ secrets.PASSWORD }}
      - name: print var
        run: echo ${{ vars.EMAIL }}