name: download

on:
  push:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Math result
        run: expr 2 + 2 > result.txt
      - name: uploud artifact
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: result.txt
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: result
      - name: show result
        run: cat result.txt