run-name: workflow_run
name: workflow_run

on:
  workflow_run:
    workflows: [fist ws]
    types:
        - completed

jobs:
  job_1:
    runs-on: ubuntu-latest
    if: ${{  github.event.workflow_run.conclusion == 'success' }}
    steps:
     - run: |
        pwd
        ls

  job_2:
    runs-on: ubuntu-latest
    if  : ${{  github.event.workflow_run.conclusion == 'failure' }}
    steps:
        - run: java -version
