run-name: workflow_run
name: workflow_run

on:
  workflow_run:
    workflows: [fist ws]
    types:
        - completed

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
     - run: |
        pwd
        ls